<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h2>Basic States</h2>
<h3>Echolib Testing with the following: </h3>
<?php print_r($state);?>
<?php foreach ($state as $key): ?>
  <ol><?= $key ?></ol>
<?php endforeach; ?>

<p>Just a little props: </p>
<?php print_r($props);?>

</body>
</html>
