<!--WHAT'S IN IT FOR YOU?-->
<section id="benefits" class="it-for-you">
    <div class="container">
        <h3 class="it-for-you__title">What’s in it for you?</h3>
        <h4 class="it-for-you__desc">Turn high-quality academic services and wow discounts into income with CashDuck.</h4>

        <div class="it-for-you__wrap">
            <div class="it-for-you__el">
                <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-1.svg" alt="booomers.club">
                <div class="it-for-you__el_title">Zero risk</div>
                <div class="it-for-you__el_desc">
                    We offer industry-leading commissions and <br> require no credit card details, registration or exit <br> fees, upfront payment or money investment.
                </div>
            </div>
            <div class="it-for-you__el">
                <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-2.svg" alt="booomers.club">
                <div class="it-for-you__el_title">Unlimited earnings</div>
                <div class="it-for-you__el_desc">
                    You get paid for every conversion with no referral<br> limit and receive a commission every time you or<br> your referrals make a new order on our websites.
                </div>
            </div>
            <div class="it-for-you__el">
                <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-3.svg" alt="booomers.club">
                <div class="it-for-you__el_title">Passive income</div>
                <div class="it-for-you__el_desc">
                    On average, each customer places 3+ orders on our<br> websites totaling $200 each, so you have<br> continuous money coming in with minimal activity.
                </div>
            </div>
            <div class="it-for-you__el">
                <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-4.svg" alt="booomers.club">
                <div class="it-for-you__el_title">Flexible schedule</div>
                <div class="it-for-you__el_desc">
                    As our affiliate, you can earn money from the<br> comfort of your home or office, in your spare time<br> or during the work hours — it’s all up to you.
                </div>
            </div>
            <div class="it-for-you__el">
                <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-5.svg" alt="booomers.club">
                <div class="it-for-you__el_title">Payouts whenever needed</div>
                <div class="it-for-you__el_desc">
                    You can choose to receive income daily, weekly or<br> monthly to PayPal or transfer it to your CashDuck<br> bonus balance and use to pay for next orders.
                </div>
            </div>
            <div class="it-for-you__el">
                <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-6.svg" alt="booomers.club">
                <div class="it-for-you__el_title">Professional support</div>
                <div class="it-for-you__el_desc">
                    You get access to a dedicated affiliate manager<br> who will give personalized advice and answer any<br> questions you have about our program.
                </div>
            </div>
        </div>




        <!-- Swiper -->
        <div class="it-for-you__swiper-container">
            <div class="swiper-wrapper it-for-you__swiper-wrapper">
                <div class="swiper-slide">
                    <div class="it-for-you__el">
                        <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-1.svg" alt="booomers.club">
                        <div class="it-for-you__el_title">Zero risk</div>
                        <div class="it-for-you__el_desc">
                            We offer industry-leading commissions and require no credit card details, registration or exit fees, upfront payment or money investment.
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="it-for-you__el">
                        <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-2.svg" alt="booomers.club">
                        <div class="it-for-you__el_title">Unlimited earnings</div>
                        <div class="it-for-you__el_desc">
                            You get paid for every conversion with no referral limit and receive a commission every time you or your referrals make a new order on our websites.
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="it-for-you__el">
                        <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-3.svg" alt="booomers.club">
                        <div class="it-for-you__el_title">Passive income</div>
                        <div class="it-for-you__el_desc">
                            On average, each customer places 3+ orders on our websites totaling $200 each, so you have continuous money coming in with minimal activity.
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="it-for-you__el">
                        <img src="<?= $base_url ?>/assets/home/img/whats-in-it-for-you-4.svg" alt="booomers.club">
                        <div class="it-for-you__el_title">Flexible schedule</div>
                        <div class="it-for-you__el_desc">
                            As our affiliate, you can earn money from the comfort of your home or office, in your spare time or during the work hours — it’s all up to you.
                        </div>
                    </div>
                </div>
                <!--                <div class="swiper-slide">-->
                <!--                    <div class="it-for-you__el">-->
                <!--                        <img src="--><?//= $base_url ?><!--/assets/home/img/whats-in-it-for-you-5.svg" alt="booomers.club">-->
                <!--                        <div class="it-for-you__el_title">Payouts whenever needed</div>-->
                <!--                        <div class="it-for-you__el_desc">-->
                <!--                            You can choose to receive income daily, weekly or monthly to PayPal or transfer it to your CashDuck bonus balance and use to pay for next orders.-->
                <!--                        </div>-->
                <!--                    </div>-->
                <!--                </div>-->
                <!--                <div class="swiper-slide">-->
                <!--                    <div class="it-for-you__el">-->
                <!--                        <img src="--><?//= $base_url ?><!--/assets/home/img/whats-in-it-for-you-6.svg" alt="booomers.club">-->
                <!--                        <div class="it-for-you__el_title">Professional support</div>-->
                <!--                        <div class="it-for-you__el_desc">-->
                <!--                            You get access to a dedicated affiliate manager who will give personalized advice and answer any questions you have about our program.-->
                <!--                        </div>-->
                <!--                    </div>-->
                <!--                </div>-->
            </div>
            <!-- Add Arrows -->
            <div class="it-for-you__button_next"></div>
            <div class="it-for-you__button_prev"></div>
        </div>


    </div>
</section>