<!--TESTIMONIALS-->
<section id="testimonials" class="testimonials">
    <div class="container">
        <h3 class="testimonials__title">Testimonials</h3>
        <h4 class="testimonials__desc">Check out what our partners are saying about their experience and results.</h4>

        <!-- Swiper -->
        <div class="swiper-container testimonials__slider_wrap">
            <div class="swiper-wrapper">
                <div class="swiper-slide testimonials__slide_content-wrap">
                    <img src="<?= $base_url ?>/assets/home/img/testimonials-slide-1.png"
                         alt="booomers.club">

                    <div class="testimonials__slide_comment-wrap">
                        <p>I have tried dozens of affiliate programs over my years online, and I have to say that
                            CashDuck is one of the best on the market! Their amazing affiliate managers, easy-to-use
                            dashboard and program have made it easy for me to promote their services and make
                            $75,000 a year just sitting on my sofa. It is something I promote with confidence and
                            without hesitation.</p>
                        <div class="testimonials__slide_person-wrap">
                            <p class="testimonials__slide_person-name">Ezra F., UAE</p>
                            <p class="testimonials__slide_person-desc">Partner since 2010</p>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide testimonials__slide_content-wrap">
                    <img src="<?= $base_url ?>/assets/home/img/testimonials-slide-2.png"
                         alt="booomers.club">

                    <div class="testimonials__slide_comment-wrap">
                        <p>I found CashDuck to be superb. Very clear and quick. Overall, prompt payouts via PayPal,
                            seamless user experience, some cool services and awesome bonus balance concept. I look
                            forward to bringing in more new customers in the future, making a greater amount of money
                            and using it to cover my academic needs as well.</p>
                        <div class="testimonials__slide_person-wrap">
                            <p class="testimonials__slide_person-name">Sun K., United Kingdom</p>
                            <p class="testimonials__slide_person-desc">Partner since 2014</p>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide testimonials__slide_content-wrap">
                    <img src="<?= $base_url ?>/assets/home/img/testimonials-slide-3.png"
                         alt="booomers.club">

                    <div class="testimonials__slide_comment-wrap">
                        <p>Fab idea! A great way to refer quality academic services to your friends and colleagues and
                            get passive income along the way. Simple to use, zero hassle with any aspect of the
                            transaction, excellent service, and execution. I was able to earn and be paid over $5,500 in
                            less than a month! Can't believe I haven't come across this before!</p>
                        <div class="testimonials__slide_person-wrap">
                            <p class="testimonials__slide_person-name">John N., USA</p>
                            <p class="testimonials__slide_person-desc">Partner since 2016</p>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide testimonials__slide_content-wrap">
                    <img src="<?= $base_url ?>/assets/home/img/testimonials-slide-4.png"
                         alt="booomers.club">

                    <div class="testimonials__slide_comment-wrap">
                        <p>Have used CashDuck to refer many of my friends for services they really need, made some money
                            for myself while helping others get rid of academic stress. It's a rare and rewarding
                            combination. Also, super well-designed, stylish and easy to use websites with friendly
                            interfaces. I quickly received my rewards and for sure will continue spreading the word.
                            Would recommend to everyone.</p>
                        <div class="testimonials__slide_person-wrap">
                            <p class="testimonials__slide_person-name">Maria H., Germany</p>
                            <p class="testimonials__slide_person-desc">Partner since 2012</p>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide testimonials__slide_content-wrap">
                    <img src="<?= $base_url ?>/assets/home/img/testimonials-slide-5.png"
                         alt="booomers.club">

                    <div class="testimonials__slide_comment-wrap">
                        <p>Made surprisingly decent amount of money and even started using their services myself as I’m
                            a student too. They offer high-quality services that I can feel confident promoting to my
                            friends and colleagues. It’s also a pretty clear process and easy to use. Why haven’t I
                            found this program some years ago?!!</p>
                        <div class="testimonials__slide_person-wrap">
                            <p class="testimonials__slide_person-name">Gabriel H., Australia</p>
                            <p class="testimonials__slide_person-desc">Partner since 2018</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Add Arrows -->
            <div class="testimonials__button_next"></div>
            <div class="testimonials__button_prev"></div>
        </div>
    </div>
    <div id="join-now-scroll-success">
        <div id="join-now-scroll" class="join-now-scroll">
            <div class="container container_mobile">
                <div id="join-now" class="testimonials__contact-form_wrap">
                    <div class="testimonials__title_form">Sign up & start making money today!</div>
                    <form id="testimonials-form" action="https://booomers.club/wp-content/special/mail.php"
                          method="post"
                          role="form">
                        <div id="testimonials-contact-form" class="testimonials__contact-form">
                            <div class="testimonials__contact-form_left">

                                <input id="formName" type="text" autocomplete="off" class="input" name="name"
                                       placeholder="First name" maxlength="10" minlength="3" required>


                                <input id="formEmail" type="email" autocomplete="off" class="input" name="email"
                                       placeholder="Email" required>

                                <div class="testimonials__form-group_checkbox-wrap-all">
                                    <p>Preferred income model</p>
                                    <div class="testimonials__form-group_checkbox-wrap">
                                        <div class="testimonials__form-group_checkbox">
                                            <input id="formOrderBased" type="checkbox" autocomplete="off"
                                                   class="checkbox input"
                                                   name="order_based" value='1'>
                                            <label for="formOrderBased">Order-Based</label>
                                        </div>
                                        <div class="testimonials__form-group_checkbox">
                                            <input id="formReferral" type="checkbox" autocomplete="off"
                                                   class="checkbox input"
                                                   name="referral" value='2'>
                                            <label for="formReferral">Referral</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="testimonials__contact-form_right">

                                <input id="formLastName" type="text" autocomplete="off" class="input" name="last-name"
                                       placeholder="Last name" maxlength="20" minlength="3" required>

                                <div class="testimonials__form-group testimonials__mobile-number_wrap">
                                    <input id="formPhoneNumber" type="tel" class="input" name="phone-number"
                                           placeholder="Phone number" maxlength="14" minlength="8"
                                           onkeypress="validateInput(event)" required>
                                    <label class="testimonials__phone-number_label" for="formPhoneNumber">Don't worry,
                                        your
                                        phone number is kept private.</label>
                                </div>

                                <button value="Submit" id="submit" name="submit"
                                        class="testimonials__contact-form_submit"
                                        type="submit">SIGN UP
                                </button>
                            </div>
                        </div>
                    </form>
                </div>

                <!----------------->

                <div id="success-email" class="testimonials__contact-form-success_wrap" style="display: none;">

                    <div id="note"></div>

                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="testimonials__questions">
            <div class="testimonials__questions_title">Have Questions About the Program?</div>
            <div class="testimonials__questions_desc">We’d love to hear from you. Here’s how to get in touch with us:
            </div>
            <div class="testimonials__questions_contact">
                <a href="mailto:support@booomers.club"
                   onclick="gtag('event', 'Support_email', { 'event_category':'Support_email'});"><img
                            src="<?= $base_url ?>/assets/home/img/message-icon.svg"
                            alt="booomers.club">support@booomers.club</a>
                <a href="tel:+13239772810" onclick="gtag('event', 'Phone_number', { 'event_category':'Phone_number'});"><img
                            src="<?= $base_url ?>/assets/home/img/phone-icon.svg"
                            alt="booomers.club">+1 (323) 977 2810</a>
            </div>
        </div>

    </div>
</section>