<!--EchoHTML Template-->
<!doctype html>
<html lang="en-US">
<head id="up">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booomers.club | With you, we engineer viral marketing through our affiliate Club</title>
    <link rel="shortcut icon" href="<?= $base_url ?>/assets/home/img/favicon.ico"
          type="image/x-icon">

    <!-- Global site tag (gtag.js) - Google Analytics -->
<!--    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-138911405-1"></script>-->
<!--    <script>-->
<!--        window.dataLayer = window.dataLayer || [];-->
<!--        function gtag() {-->
<!--            dataLayer.push(arguments);-->
<!--        }-->
<!--        gtag('js', new Date());-->
<!---->
<!--        gtag('config', 'UA-138911405-1');-->
<!--    </script>-->



    <!-- All in One SEO Pack 2.10.1 by Michael Torbert of Semper Fi Web Design[158,177] -->
    <meta name="description"  content="Looking to earn while you share stuffs on social media while you invite others  ? Look no further, Booomers.club got your back on that." />

    <link rel="canonical" href="https://booomers.club/" />
    <!-- /all in one seo pack -->
    <link rel='dns-prefetch' href='//ajax.googleapis.com' />
    <link rel='dns-prefetch' href='//s.w.org' />
    <link rel='stylesheet' id='style-css'  href='<?= $base_url ?>/assets/home/css/style.min.css' type='text/css' media='all' />
    <link rel='stylesheet' id='swiper-style-css'  href='<?= $base_url ?>/assets/home/css/plugins/swiper.min.css' type='text/css' media='all' />
</head>

<body class="home page-template page-template-front-page page-template-front-page-php page page-id-2">

<header class="header fixed" id="header">
    <div class="container">
        <div class="nav-wrapper">
            <div class="logo">
                <a class="logo-link" href="https://booomers.club">
                    <img class="logo-img" src="<?= $base_url ?>/assets/home/img/logo.png"
                         alt="booomers.club"/>
                </a>
            </div>


            <!--MAIN-MENU-->
            <div class="nav">
                <ul id="menu-top-menu" class="menu">
<!--                    <li id="menu-item-35" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-35"><a href="#benefits">Benefits</a></li>-->
<!--                    <li id="menu-item-36" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-36"><a href="#order-based-model">Order-based model</a></li>-->
<!--                    <li id="menu-item-37" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-37"><a href="#referral-based-model">Referral model</a></li>-->
                    <li id="menu-item-38" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-38"><a href="#how-it-works">How it works</a></li>
<!--                    <li id="menu-item-39" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-39"><a href="#testimonials">Testimonials</a></li>-->
                </ul>
            </div>


<!--            <a href="#yt-intro">-->
<!--                Take an Intro Tour &nbsp-->
<!--                <button id="openNavMains" class="btn btn-menu header__mobile-menu">-->
<!--                    <svg class="ham hamRotate ham8" viewBox="0 0 100 100" width="80" onclick="this.classList.toggle('active')">-->
<!--                        <path-->
<!--                            class="line top"-->
<!--                            d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20" />-->
<!--                        <path-->
<!--                            class="line middle"-->
<!--                            d="m 30,50 h 40" />-->
<!--                        <path-->
<!--                            class="line bottom"-->
<!--                            d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20" />-->
<!--                    </svg>-->
<!--                </button>-->
<!--            </a>-->
            <div class="header__btn">
<!--                <a href="./login">Sign in</a>-->
<!--                <a href="./join">Join Us</a>-->
<!--                <a href="./login">Sign in</a>-->
                <a href="https://join.booomers.club">Join Us Now</a>
            </div>

        </div>
    </div>
</header>

<div id="sidenavMains" class="sidenavs">
    <ul id="menu-top-menu-1" class="nav menu">
<!--        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-35"><a href="#benefits">Benefits</a></li>-->
<!--        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-36"><a href="#offer-based-model">Offer-based model</a></li>-->
<!--        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-37"><a href="#referral-based-model">Referral model</a></li>-->
        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-38"><a href="#how-it-works">How it works</a></li>
<!--        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-39"><a href="#testimonials">Testimonials</a></li>-->
    </ul></div>
<div class="overlay"></div>


<!--MAIN-->
<div id="main" class="main">
    <!--TOP-BLOCK-->
    <section class="top-block">
        <div class="container flex-container top-block__container">
            <div class="top-block__flex-left">
                <h1 class="top-block__title">
                    <span>Get paid</span> for Sharing stuffs</br>
                    on social media &</br> referring everyone you know
                </h1>
                <h2 class="top-block__desc">
                    There's no limit on how much you can earn,
                    and it's super easy to get started.
                </h2>
                <div class="top-block__btn-container">
<!--                    <div class="top-block__btn1">-->
<!--                        <a href="./login">Sign In</a>-->
<!--                    </div>-->
                    <div class="top-block__btn2">
                        <a href="https://join.booomers.club">Join the Waitlist</a>
                    </div>
                </div>
            </div>

            <div class="top-block__flex-right">
                <img src="<?= $base_url ?>/assets/home/img/top-block.png" alt="booomers.club">
            </div>

            <div class="top-block__advantages">
                <div class="top-block__advantages-box2">
                    <div class="top-block__advantages-box_content">
                        <span>Regular tax-free payouts via</span>
                        <img src="<?= $base_url ?>/assets/home/img/cashout.png" alt="booomers.club">
                    </div>
                </div>
                <!--            <div class="top-block__advantages-box2">-->
                <!--                <div class="top-block__advantages-box_content">-->
                <!--                    <span>Years at the top</span>-->
                <!--                    <p>10+</p>-->
                <!--                </div>-->
                <!--            </div>-->
                <div class="top-block__advantages-box3">
                    <div class="top-block__advantages-box_content">
                        <span>Money Back Guarantee</span>
                        <p>Zero Risk</p>
                    </div>
                </div>
                <!--            <div class="top-block__advantages-box4">-->
                <!--                <div class="top-block__advantages-box_content">-->
                <!--                    <span>Active partners</span>-->
                <!--                    <p>700+</p>-->
                <!--                </div>-->
                <!--            </div>-->
            </div>
        </div>
    </section>

    <!--Benefits-->

    <!--HOW-DOES-IT-WORK-->
    <section id="how-it-works" class="how-does-it-work">
        <div class="container">
            <h3 class="how-does-it-work__title">How does it work?</h3>
            <h4 class="how-does-it-work__desc">Designed for everyone, Booomers.club makes it simple to:</h4>

            <div class="how-does-it-work__wrap">
                <div class="how-does-it-work__el">
                    <img src="<?= $base_url ?>/assets/home/img/how-does-it-work-1.svg" alt="booomers.club">
                    <div class="how-does-it-work__el_sticker">Step 1</div>
                    <div class="how-does-it-work__el_title">Get started</div>
                    <div class="how-does-it-work__el_desc">
                        To join our affiliate club, fill out a quick registration form. It’s requires a fee, completely confidential and takes less than 5 minutes.
                    </div>
                    <div class="how-does-it-work__el_btn">
                        <a href="https://join.booomers.club">join now</a>
                    </div>
                </div>
                <div class="how-does-it-work__el">
                    <img src="<?= $base_url ?>/assets/home/img/how-does-it-work-2.svg" alt="booomers.club">
                    <div class="how-does-it-work__el_sticker">Step 2</div>
                    <div class="how-does-it-work__el_title">Promote</div>
                    <div class="how-does-it-work__el_desc">
                        Once enrolled, Sharing or spread the word about our offers through the appropriate social media channels required or just refer others who can to the club using your referral link.
                    </div>
                    <div class="how-does-it-work__el_btn">
                        <a href="https://join.booomers.club">join now</a>
                    </div>
                </div>
                <div class="how-does-it-work__el">
                    <img src="<?= $base_url ?>/assets/home/img/how-does-it-work-3.svg" alt="booomers.club">
                    <div class="how-does-it-work__el_sticker">Step 3</div>
                    <div class="how-does-it-work__el_title">Earn a commission</div>
                    <div class="how-does-it-work__el_desc">
                        Based on your promotions, Earn points worth money in your currency when provide screenshot after 23 hours of sharing an offer or Instantly earn 20% commission/cashback when your leads convert.
                    </div>
                    <div class="how-does-it-work__el_btn">
                        <a href="https://join.booomers.club">join now</a>
                    </div>
                </div>
                <div class="how-does-it-work__el">
                    <img src="<?= $base_url ?>/assets/home/img/how-does-it-work-4.svg" alt="booomers.club">
                    <div class="how-does-it-work__el_sticker">Step 4</div>
                    <div class="how-does-it-work__el_title">Get paid</div>
                    <div class="how-does-it-work__el_desc">
                        Make money on the promotions you do and maybe memberships royalties, cashout straight to your preferred Mobile Money wallet.
                    </div>
                    <div class="how-does-it-work__el_btn-wrap">
                        <div class="how-does-it-work__el_btn">
                            <a href="https://join.booomers.club">join now</a>
                        </div>
                    </div>
                </div>
            </div>



            <!-- Swiper -->
            <div class="how-does-it-work__swiper-container">
                <div class="swiper-wrapper how-does-it-work__swiper-wrapper">
                    <div class="swiper-slide">
                        <div class="how-does-it-work__el">
                            <img src="<?= $base_url ?>/assets/home/img/how-does-it-work-1.svg" alt="booomers.club">
                            <div class="how-does-it-work__el_sticker">Step 1</div>
                            <div class="how-does-it-work__el_title">Get started</div>
                            <div class="how-does-it-work__el_desc">
                                To join our affiliate club, fill out a quick registration form. It’s requires a fee, completely confidential and takes less than 5 minutes.
                            </div>
                            <div class="how-does-it-work__el_btn">
                                <a href="https://join.booomers.club">join now</a>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="how-does-it-work__el">
                            <img src="<?= $base_url ?>/assets/home/img/how-does-it-work-2.svg" alt="booomers.club">
                            <div class="how-does-it-work__el_sticker">Step 2</div>
                            <div class="how-does-it-work__el_title">Promote</div>
                            <div class="how-does-it-work__el_desc">
                                Once enrolled, Sharing or spread the word about our offers through the appropriate social media channels required or just refer others who can to the club using your referral link.
                            </div>
                            <div class="how-does-it-work__el_btn">
                                <a href="https://join.booomers.club">join now</a>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="how-does-it-work__el">
                            <img src="<?= $base_url ?>/assets/home/img/how-does-it-work-3.svg" alt="booomers.club">
                            <div class="how-does-it-work__el_sticker">Step 3</div>
                            <div class="how-does-it-work__el_title">Earn a commission</div>
                            <div class="how-does-it-work__el_desc">
                                Based on your promotions, Earn points worth money in your currency when provide screenshot after 23 hours of sharing an offer or Instantly earn 20% commission/cashback when your leads convert.
                            </div>
                            <div class="how-does-it-work__el_btn">
                                <a href="https://join.booomers.club">join now</a>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="how-does-it-work__el">
                            <img src="<?= $base_url ?>/assets/home/img/how-does-it-work-4.svg" alt="booomers.club">
                            <div class="how-does-it-work__el_sticker">Step 4</div>
                            <div class="how-does-it-work__el_title">Get paid</div>
                            <div class="how-does-it-work__el_desc">
                                Make money on the promotions you do and maybe memberships royalties, cashout straight to your preferred Mobile Money wallet.
                            </div>
                            <div class="how-does-it-work__el_btn-wrap">
                                <div class="how-does-it-work__el_btn">
                                    <a href="https://join.booomers.club">join now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Add Pagination -->
                <div class="how-does-it-work__swiper-pagination"></div>
            </div>

        </div>
    </section>

    <!--REFERRAL-INCOME-MODEL-->
    <section id="referral-based-model" class="ref-income-model">
        <div class="container">
            <h3 class="ref-income-model__title">Who Are we, Booomers Club?</h3>
            <h4 class="ref-income-model__desc">We are an affiliate marketing club commissioned to power viral marketing campaigns with you.</h4>
        </div>
        <div class="container flex-container income-model__container">
            <div class="ref-income-model__flex-left ref-income-model__flex-left">
                <div class="ref-income-model__range">
                    <div class="ref-income-model__range_title">Boooomers is a Social Media Marketing Agency</div>
                    <div class="ref-income-model__range_desc">which means with you in this club, we create viral ads just like this:</div>

                    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5364502701400927"
                            crossorigin="anonymous"></script>
                    <!-- Booomers Ad Example -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-5364502701400927"
                         data-ad-slot="8728974747"
                         data-ad-format="auto"
                         data-full-width-responsive="true"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>

<!--                    <div class="ref-income-model__range-slider">-->
<!--                        <input id="ref-income-model-range" class="ref-income-model__range-slider_range" type="range" value="1"-->
<!--                               min="1" max="100" oninput="refRangeIncome()">-->
<!--                        <div class="ref-income-model__range_output-wrap">-->
<!---->
<!--                            <output id="ref-income-model-range-output" class="ref-income-model__range_output" name="output"-->
<!--                                    for="range">-->
<!--                                1-->
<!--                            </output>-->
<!---->
<!---->
<!--                        </div>-->
<!--                        <div class="ref-income-model__range-slider-value_wrap">-->
<!--                            <span class="ref-income-model__range-slider_value">1</span>-->
<!--                            <span class="ref-income-model__range-slider_value">100</span>-->
<!--                        </div>-->
<!--                    </div>-->

                    <div class="ref-income-model__range-bottom_wrap">
                        <div class="ref-income-model__range-bottom_price">
                            <p class="ref-income-model__range-bottom_price-title">You have earned it</p>
                            <p id="ref-income-model-count" class="ref-income-model__range-bottom_price-count">DONT <span>miss out</span></p>
                        </div>
                        <div class="ref-income-model__range-bottom_btn">
                            <a href="#join-now-scroll" onclick="gtag('event', 'apply_now', {'event_category': 'Order_based_model'});">Join now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ref-income-model__flex-right ref-income-model__flex-right">

                <div class="ref-income-model__ribbons_desc">
                    While sharing your offers on Facebook, Twitter, WhatsApp or other social networks is fun already, you can earn this way much more.
                    <br/> <br/> Our models are simple: everyone who participates gets points for sharing offers.
                    Now you can get up to 20% commission on each member referral and up to 10% cashback / commission on each deal done!
                </div>
                <div class="ref-income-model__ribbons-wrap">
                    <div class="ref-income-model__ribbons-el ref-income-model__ribbons-el-animate">
                        <div class="ref-income-model__ribbons-el_title">
                            <p>Offers</p>
                            <p><span>Experience Level:</span> Novice</p>
                        </div>
<!--                        <div class="ref-income-model__ribbons-el_cash">-->
<!--                            <p><span>$</span>4,500+</p>-->
<!--                        </div>-->
                        <div class="ref-income-model__ribbons-el_desc">
                            <p><img src="<?= $base_url ?>/assets/home/img/ribbons-star.svg"
                                    alt="booomers.club"><span>Points:</span> valued by offer</p>
<!--                            <p><img src="--><?//= $base_url ?><!--/assets/home/img/ribbons-cash.svg"-->
<!--                                    alt="booomers.club"><span>Your cashback:</span> 20%</p>-->
                        </div>
                    </div>
                    <div class="ref-income-model__ribbons-el">
                        <div class="ref-income-model__ribbons-el_title">
                            <p>Referals</p>
                            <p><span>Experience Level:</span> Beginner</p>
                        </div>
<!--                        <div class="ref-income-model__ribbons-el_cash">-->
<!--                            <p><span>$</span>2,100+</p>-->
<!--                        </div>-->
                        <div class="ref-income-model__ribbons-el_desc">
<!--                            <p><img src="--><?//= $base_url ?><!--/assets/home/img/ribbons-star.svg"-->
<!--                                    alt="booomers.club"><span>Fixed reward:</span> 20%</p>-->
                            <p><img src="<?= $base_url ?>/assets/home/img/ribbons-cash.svg"
                                    alt="booomers.club"><span>Commision:</span> 20%</p>
                        </div>
                    </div>
                    <div class="ref-income-model__ribbons-el">
                        <div class="ref-income-model__ribbons-el_title">
                            <p>Deals</p>
                            <p><span>Experience Level:</span> Intermediate</p>
                        </div>
<!--                        <div class="ref-income-model__ribbons-el_cash">-->
<!--                            <p><span>$</span>800+</p>-->
<!--                        </div>-->
                        <div class="ref-income-model__ribbons-el_desc">
<!--                            <p><img src="--><?//= $base_url ?><!--/assets/home/img/ribbons-star.svg"-->
<!--                                    alt="booomers.club"><span>Fixed reward:</span> $500</p>-->
                            <p><img src="<?= $base_url ?>/assets/home/img/ribbons-cash.svg"
                                    alt="booomers.club"><span>Your cashback/commision:</span> 5%-10%/deal</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>


    <script>
        function validateInput(evt) {
            var theEvent = evt || window.event;
            var key = theEvent.keyCode || theEvent.which;
            key = String.fromCharCode(key);
            var regex = /[0-9-)(]|\./;
            if (!regex.test(key)) {
                theEvent.returnValue = false;
                if (theEvent.preventDefault) theEvent.preventDefault();
            }
        }

    </script>
</div>
<footer class="footer">

    <div class="container">
        <div class="footer__nav-wrap">
            <div class="footer__logo">
                <a class="footer__logo_link" href="#up">
                    <img class="footer__logo_img" src="<?= $base_url ?>/assets/home/img/logo-footer.png"
                         alt="booomers.club"/>
                </a>
            </div>

<!---->
            <!--FOOTER-MENU-->
            <div class="footer__nav">
                <ul id="menu-bottom-menu" class="menu">
<!--                    <li id="menu-item-40" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-40"><a href="#benefits">Benefits</a></li>-->
<!--                    <li id="menu-item-41" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-41"><a href="#order-based-model">Order-based model</a></li>-->
<!--                    <li id="menu-item-42" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-42"><a href="#referral-based-model">Referral model</a></li>-->
                    <li id="menu-item-43" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-43"><a href="#how-it-works">How it works</a></li>
<!--                    <li id="menu-item-44" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-44"><a href="#testimonials">Testimonials</a></li>-->
                </ul>
            </div>

        </div>
        <div class="footer__copyright">
            © 2021 All Rights Reserved. Booomers is a Social Media Marketing Agency, businesses should contact <a
                    href="tel:+233557392027">+233 (0)55 739 2027 (WhatsApp)</a> or <a href="mailto:promote@booomers.club" class="text-warning">promote@booomers.club (Email)</a>
        </div>
    </div>

</footer>


<script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js?ver=3.3.1'></script>
<script type='text/javascript' src='<?= $base_url ?>/assets/home/js/plugins/swiper.min.js'></script>
<script type='text/javascript' src='<?= $base_url ?>/assets/home/js/main.min.js'></script>

</body>
</html>
